version: 2
models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing
        data_tests:
          - unique
          - not_null
      - name: host_id
        description: The hosts's id. References the host table.
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: room_type
        description: Type of the apartment / room
        data_tests:
          - accepted_values:
              values:
                - Entire home/apt
                - Private room
                - Shared room
                - Hotel room
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_value
      - name: price
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 5000
              strictly: false
              config:
                severity: warn
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.95
              min_value: 50
              max_value: 500
  - name: dim_hosts_cleansed
    columns:
      - name: host_id
        data_tests:
          - not_null
          - unique
      - name: host_name
        data_tests:
          - not_null
      - name: is_superhost
        data_tests:
          - accepted_values:
              values:
                - t
                - f
  - name: dim_listings_w_hosts
    data_tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
  - name: fct_reviews
    columns:
      - name: listing_id
        data_tests:
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id
      - name: reviewer_name
        data_tests:
          - not_null
      - name: review_sentiment
        data_tests:
          - accepted_values:
              values:
                - positive
                - neutral
                - negative
  - name: full_moon_reviews
    columns:
      - name: review_id
        data_type: varchar
      - name: listing_id
        data_type: number
      - name: review_date
        data_type: timestamp_ntz
      - name: reviewer_name
        data_type: varchar
      - name: review_text
        data_type: varchar
      - name: review_sentiment
        data_type: varchar
        tests:
          - accepted_values:
              values:
                - neutral
                - positive
                - negative
      - name: is_full_moon
        data_type: varchar
